server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgresql:5432/bookdb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: book-service
  cloud:
    config:
      uri: http://config-service:8888
    discovery:
      enabled: true
  config:
    import: "optional:configserver:"

management:
  endpoints:
    web:
      exposure:
        include: health,info
