spring:
  application:
    name: book-service
  cloud:
    config:
      uri: http://localhost:8888
    discovery:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/