server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AndreMIsidoro/java.git
          search-paths: projects/bookstore-config
          default-label: master




management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always